### ISSUE TITLE
Connect DBMS

### ISSUE THREAD

**Issue by Vishwaak** [Vishwaak/Taxi_ShareIty#1]
#Issue 1:
Connect a Databases system for the constructed front end part of program

To Run:
The front end was constructed using the Netbeans IDE . Use the same ide for the construction of the project.

**Comment by espoand** [comment]
Hi, do you need only the connection to the database? i can work on this, but specify a db to use.

**Comment by Vishwaak** [comment]
It would be awesome if you can connect it could use  MySQL. Main idea of connecting a DB is for the purpose of registration and logging in. @espoand

**Comment by espoand** [comment]
ok, can you assign me this issue?
