### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Vishwaak** [Vishwaak/Taxi_ShareIty#13]
Design a new logo for the application and added it to the login screen.

**Comment by whitek2** [comment]
Hiyah!
How would you like for it to be added to the login screen? Would you just like me to attach it here as a PNG file? I'm unsure what exactly is meant

**Comment by Vishwaak** [comment]
@whitek2  It would be awesome if you can added it to the login screen.

**Comment by Vishwaak** [comment]
#18 and #13 :+1:  two awesome PR's which solve the problem. If any further improvement feel free to reopen the issue. :smiley:
