### ISSUE TITLE
Encrypt Password

### ISSUE THREAD

**Issue by Vishwaak** [Vishwaak/Taxi_ShareIty#3]
Right now the password is directly being passed to the database . When we store the password it needs to be encrypted .

**Comment by PedroCisnerosSantana** [comment]
I will take a look at the code and try to encrypt it

**Comment by espoand** [comment]
hi, i can so the issue.

**Comment by julcaesar** [comment]
@Vishwaak , it's wrong to decrypt password Hash that inserted to database,  it should be irreversible.
for login you should compare 2 hash code(One in database table and another one is convert the password from user )

**Comment by Vishwaak** [comment]
@julcaesar considering what you mentioned about , I guess we can use the private key to encrypt the password and then check their hash to validate them.

**Comment by Vishwaak** [comment]
PR #6 solves the issue . Closing as the requested changes are made.
