### ISSUE TITLE
Registration Form (Backed)

### ISSUE THREAD

**Issue by Vishwaak** [Vishwaak/Taxi_ShareIty#4]
**Currently the registration form contains the following** 
          - Username
          - Password
          - Contact_no
          - Email_id
          -Choice between Students and Driver
Following Conditions to check:
                   1. Check if all fields are non empty
                    2.Username ,contact_no and email_id needs to be unique.

**Comment by espoand** [comment]
can you assign to me?

**Comment by Vishwaak** [comment]
Yeah sure feel free to work on it. @espoand

**Comment by Vishwaak** [comment]
PR #10  fixes the issue . Good work on completing it @espoand  :slightly_smiling_face:
